### ISSUE TITLE
Adapt to the new tensorflow version

### ISSUE THREAD

**Issue by PositivPy** [ironhide23586/RoomNet#3]
## Error
The new tensorflow version (2.0)  has a different API;
```
Traceback (most recent call last):
  File "app.py", line 21, in <module>
    nn = RoomNet(num_classes=len(CLASS_LABELS), im_side=IMG_SIDE, compute_bn_mean_var=False,
  File "/RoomNet/network.py", line 28, in __init__
    self.x_tensor = tf.placeholder(tf.float32, shape=[None, im_side, im_side, 3],
AttributeError: module 'tensorflow' has no attribute 'placeholder'
```
## Solution 
In `./network.py` replace the tensorflow import with;
```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```

**Comment by ironhide23586** [comment]
legacy codebase - closing
